-- Lua class for managing story_objects.

local story_obj_registry = nil

class "story_objects_registry"

function story_objects_registry:__init ()
	self.id_by_story_id = {}
	self.story_id_by_id = {}
end

function recive_client(packet)
	local story_manager = get_story_objects_registry()

	local type = packet:r_u8()

	if (type == 1) then 
		local obj_id 	   = packet:r_u32()
		local story_obj_id = packet:r_stringZ()

		story_manager.id_by_story_id[story_obj_id] 		= obj_id
		story_manager.story_id_by_id[obj_id]			= story_obj_id
 	elseif (type == 2) then 
		local obj_id 	   = packet:r_u32()

		if story_manager.story_id_by_id[obj_id] ~= nil then
			story_manager.id_by_story_id[story_manager.story_id_by_id[obj_id]]	= nil
			story_manager.story_id_by_id[obj_id] 						= nil
		end

	elseif (type == 3) then
		local story_obj_id = packet:r_stringZ()
		
		if story_manager.id_by_story_id[story_id] ~= nil then
			story_manager.story_id_by_id[story_manager.id_by_story_id[story_id]]	= nil
			story_manager.id_by_story_id[story_id]						= nil
		end
	end 
end

function send_update(type, id, name) 
	
	if (type == 1) then 
		local packet = mp_events.gen_event('SYNC_STORY_SYNC')
		packet:w_u8(1) -- ADD
		packet:w_u32(id)
		packet:w_stringZ(name)
		mp_events.send_broadcast(packet)
	elseif (type == 2) then 
		local packet = mp_events.gen_event('SYNC_STORY_SYNC')
		packet:w_u8(2) -- REMOVE BY ID
		packet:w_u32(id)
 		mp_events.send_broadcast(packet)
	elseif (type == 3) then
		local packet = mp_events.gen_event('SYNC_STORY_SYNC')
		packet:w_u8(3) -- REMOVE BY name
 		packet:w_stringZ(name)
		mp_events.send_broadcast(packet)
	end
end

function story_objects_registry:register(obj_id , story_obj_id, on_register)
	if self.id_by_story_id[story_obj_id] ~= nil then
		if obj_id ~= self.id_by_story_id[story_obj_id] then
			local exist_obj_name = alife():object(self.id_by_story_id[story_obj_id]):name()
			local adding_obj_name = alife():object(obj_id):name()
			abort("You are trying to spawn two or more objects with the same story_id:[%s] --> [%s] try to add:[%s]", story_obj_id, exist_obj_name, adding_obj_name)
		end
	elseif self.story_id_by_id[obj_id] ~= nil then
		if self.story_id_by_id[obj_id] ~= story_obj_id then
			abort("Object [%s] is already in story_objects_registry with story_id[%s]", tostring(obj_id), story_obj_id)
		end
	end
	self.id_by_story_id[story_obj_id] 	= obj_id
	self.story_id_by_id[obj_id]			= story_obj_id

	--mp.add_story(obj_id, story_obj_id)

	if (OnServer()) then 
		send_update(1, obj_id, story_obj_id)
	end
	
end

function story_objects_registry:unregister_by_id(obj_id)
	if self.story_id_by_id[obj_id] ~= nil then
		self.id_by_story_id[self.story_id_by_id[obj_id]]	= nil
		self.story_id_by_id[obj_id] 						= nil
	end

	--mp.del_story_byID(obj_id)

	if (OnServer()) then 
		send_update(2, obj_id)
	end
end

function story_objects_registry:unregister_by_story_id(story_id)
	if self.id_by_story_id[story_id] ~= nil then
		self.story_id_by_id[self.id_by_story_id[story_id]]	= nil
		self.id_by_story_id[story_id]						= nil
	end

	--mp.del_story_byName(story_id)

	if (OnServer()) then 
		send_update(3, nil, story_obj_id)
	end
end

function story_objects_registry:get(story_obj_id)
	return self.id_by_story_id[story_obj_id]
end

function story_objects_registry:get_story_id(obj_id)
	return self.story_id_by_id[obj_id]
end

function story_objects_registry:save(packet)
	set_save_marker(packet, "save", false, "story_objects")
	local count = 0
	for k,v in pairs(self.id_by_story_id) do
		count = count + 1
	end
	if count > 65534 then
		print_table(self.id_by_story_id)
		abort("There is too many story_ids!!!")
	end
	packet:w_u16(count)
	for k,v in pairs(self.id_by_story_id) do
		packet:w_stringZ(k)
		packet:w_u16(v)
	end
	set_save_marker(packet, "save", true, "story_objects")
end

function story_objects_registry:load(packet)
	set_save_marker(packet, "load", false, "story_objects")
	local count = packet:r_u16()
	for i = 1, count do
		local story_id 	= packet:r_stringZ()
		local obj_id	= packet:r_u16()
		self.id_by_story_id[story_id] 	= obj_id
		self.story_id_by_id[obj_id]		= story_id
	end
	set_save_marker(packet, "load", true, "story_objects")
 end


 function get_story_objects_registry()
	if story_obj_registry == nil then
		story_obj_registry = story_objects_registry()
	end
	return story_obj_registry
end

function check_spawn_ini_for_story_id(se_obj)
	--printf("checking obj[%s] for story_id!!!",se_obj:name())
	local spawn_ini = se_obj:spawn_ini()
	local spawn_sect = se_obj:section_name()

	if spawn_ini:section_exist("story_object") then
		local result, id, value
		result, id, value	= spawn_ini:r_line("story_object",0,"","")
		if id ~= "story_id" then
			abort("There is no 'story_id' field in [story_object] section :object [%s]", se_obj:name())
		end
		if value == "" then
			abort("Field 'story_id' in [story_object] section got no value :object [%s]", se_obj:name())
		end

		print_msg("[REGISTER] Story OBJ: " .. tostring(se_obj.id) .. " | STORY NAME: " .. tostring(value) .. " | SPAWN: " .. tostring(spawn_sect) )
		get_story_objects_registry():register(se_obj.id, value, true)
		return
	end


	spawn_ini = system_ini()

	local story_id = utils.cfg_get_string(spawn_ini, spawn_sect, "story_id", nil, false, "", nil)
	if story_id ~= nil then
		print_msg("[REGISTER] Story OBJ: " .. tostring(se_obj.id) .. " | STORY NAME: " .. tostring(story_id) .. " | SPAWN: " .. tostring(spawn_sect) )
		get_story_objects_registry():register(se_obj.id , story_id, true)
	end
end


-- CALL FROM ENGINE

function SendAllData(packet)
	local registry = get_story_objects_registry()
 
	local INDEXs = 0
	for id, story in pairs (registry.story_id_by_id) do 
		INDEXs = INDEXs + 1
	end
	
	packet:w_u32( INDEXs )
	for id, story in pairs (registry.story_id_by_id) do 
		packet:w_u32(id)
		packet:w_stringZ(story)
	end
end

function ReadAllData(packet)
	local registry = get_story_objects_registry()

	local  INDEXs = packet:r_u32()
	for id = 0, INDEXs do 
		local obj_id 		= packet:r_u32()
		local story_obj_id  = packet:r_stringZ()

		registry.id_by_story_id[story_obj_id] 		= obj_id
		registry.story_id_by_id[obj_id]				= story_obj_id
	end
end
 

--function RegisterClientStory(oID, oStory)
--	local registry = get_story_objects_registry()
--	print_msg("Register StoryID: " .. tostring(oStory) .. " | oID: " .. tostring(oID) )
--	if (registry.id_by_story_id[oID] ~= nil) then 
--		registry.id_by_story_id[story_obj_id] 	= obj_id
--		registry.story_id_by_id[obj_id]			= story_obj_id
--	end
--end
--
--function UnRegisterClientStory_id(oID)
--	local registry = get_story_objects_registry()
--
--	if  registry.story_id_by_id[oID] ~= nil then
--		registry.id_by_story_id[registry.story_id_by_id[oID]]	= nil
--		registry.story_id_by_id[oID] 						= nil
--	end
--end
--
--
--function UnRegisterClientStory_str(oStory)
--	local registry = get_story_objects_registry()
--
--	if  registry.id_by_story_id[oStory] ~= nil then
--		registry.story_id_by_id[registry.id_by_story_id[oStory]]	= nil
--		registry.id_by_story_id[oStory]							= nil
--	end
--end