----------------------------------------------------------------------------------------------------
-- Do nothing
----------------------------------------------------------------------------------------------------

local i,k,v = 0,0,0

local teleport_idle = 0
local teleport_activated = 1

class "action_teleport"
function action_teleport:__init(obj, storage)
	self.object = obj
	
	self.st = storage
	
	self.state = teleport_idle
	self.timer = nil
	
	self.state_checked = false
end

function action_teleport:update(delta)
 	local player_selected = nil
	
	for k, player in pairs (db.players) do 
		if self.object:inside(player:position()) then
			player_selected = player
			
			-- Обработка телепорта
			if self.state == teleport_idle then 
				self.state = teleport_activated
				self.timer = time_global()	
			end
		end
	end
	
	if self.state == teleport_activated and player_selected ~= nil then	
		-- Производим телепортацию
		local point_selected = nil 
 
		for k,v in pairs(self.st.points) do		
			-- Определяются допустимые состояния для лагеря.
			point_selected = v;
			break
		end
	 
 		-- Осуществляется рандомный взвешенный переход.	
		-- телепорт в выбранную точку					
		local actor_client_id 		= level.get_client_by_gameid( player_selected:id() )
		
		local actor_position 		= patrol(point_selected.point):point(0)
		local actor_direction 		= -patrol(point_selected.look):point(0):sub(patrol(point_selected.point):point(0)):getH()
		print_msg("ACTORID: " .. tostring(actor_client_id) .. " | START TELEPORT TO : Z: " .. tostring(actor_position.x) .. " | Y: " ..  tostring(actor_position.y) .. " | Z: " .. tostring(actor_position.z))

		mp.sv_teleport_player( actor_client_id, actor_position )	 --actor_direction	

		self.state = teleport_idle
	end
end

---------------------------------------------------------------------------------------------------------------------
function add_to_binder(npc, ini, scheme, section, storage)
	local action = action_teleport(npc, storage)

	-- Зарегистрировать все actions, в которых должен быть вызван метод reset_scheme при изменении настроек схемы:
	xr_logic.subscribe_action_for_events(npc, storage, action)
end

function set_scheme(obj, ini, scheme, section, gulag_name)
	local st = xr_logic.assign_storage_and_bind(obj, ini, scheme, section)
	st.logic = xr_logic.cfg_get_switch_conditions(ini, section, obj)
	
	st.timeout = utils.cfg_get_number(ini, section, "timeout", obj, false, 900)
	
	st.points = {}
	for i=1,10 do
		local t = {
			point = utils.cfg_get_string(ini, section, "point"..tostring(i), obj, false, "", "none"),
			look = utils.cfg_get_string(ini, section, "look"..tostring(i), obj, false, "", "none"),
			prob = utils.cfg_get_number(ini, section, "prob"..tostring(i), obj, false, 100)
		}
		if t.point == "none" or t.look == "none" then
			break
		end
		table.insert(st.points, t)
	end
	if #st.points == 0 then
		abort("Wrong point nums in sr_teleport [%s]", tostring(section))
	end
end

