--------------------------------------------------------------------------------
-- Surge manager class ---------------------------------------------------------
-- Made by Peacemaker ----------------------------------------------------------
-- 05.03.07 --------------------------------------------------------------------
--------------------------------------------------------------------------------
local surge_manager 		= nil

local surge_shock_pp_eff 	= 1
local earthquake_cam_eff 	= 2
local sleep_cam_eff 		= 3
local sleep_fade_pp_eff		= 4

local START_MIN_SURGE_TIME 	= 2*60*60
local START_MAX_SURGE_TIME 	= 4*60*60
local MIN_SURGE_TIME 		= 12*60*60
local MAX_SURGE_TIME 		= 24*60*60
local prev_sec 				= 0
local diff_sec 				= 0


class "CSurgeManager"
function CSurgeManager:__init()
end

function CSurgeManager:initialize()
	self.ini = ini_file("misc\\surge_manager.ltx")

	self.levels_respawn = {zaton = false, jupiter = false, pripyat = false}

	self.started = false
	self.finished = true
	self.time_forwarded = false
	self.skip_message = false

	-- NEW BY SE7KILLS SYNC VALUES (OnServer)
	self.started_weather 		= false
 
	-- END

	self.task_given 			= false
	self.effector_set 			= false
	self.second_message_given 	= false
	self.ui_disabled 			= false
	self.blowout_sound 			= false

	self.surge_time = 190
	self.inited_time = game.CTime()
	self.last_surge_time 		= game.get_game_time()
	self._delta 				= math.random(START_MIN_SURGE_TIME, START_MAX_SURGE_TIME) -- global minutes, время между выбросами
	self.last_surge_update		= game.get_game_time()

	self.count = 0
	self.covers = {}

	self.condlist = {}
	self.survive = {}

	local ini = self.ini
	local cond_string = "true"
	if(ini:line_exist("settings", "condlist")) then
		cond_string = ini:r_string("settings", "condlist")
	end
	self.condlist = xr_logic.parse_condlist(nil, "surge_manager", "condlist", cond_string)

	cond_string = "false"
	if(ini:line_exist("settings", "survive")) then
		cond_string = ini:r_string("settings", "survive")
	end
	self.survive = xr_logic.parse_condlist(nil, "surge_manager", "survive_condlist", cond_string)

	self:init_surge_covers()

	self.surge_message = ""
	self.surge_task_sect = ""

	self.loaded = false
	self.initialized = true
end

function CSurgeManager:init_surge_covers()
	local ini = self.ini
	for i = 0, ini:line_count("list")-1 do
		temp1, id, temp2 = ini:r_line("list", i, "", "")
		local zone = db.zone_by_name[id]
		if zone ~= nil then
			self.count = self.count + 1
			self.covers[self.count] = zone
			if(ini:line_exist(id, "condlist")) then
				self.covers[self.count].condlist = {}
				self.covers[self.count].condlist = xr_logic.parse_condlist(npc, id, "condlist", ini:r_string(id, "condlist"))
			end
		end
	end
end

function CSurgeManager:get_nearest_cover()
	if (self.loaded) then
		self:init_surge_covers()
	end
	
	if not (db.get_actor()) then
		return nil
	end
	
	local hides = {}
	utils.copy_table(hides, self.covers)
	
	if(self.count>0) then
		for k,v in pairs(hides) do
			if (v.condlist) then
				local sect = xr_logic.pick_section_from_condlist(db.get_actor(), nil, v.condlist)
				if(sect~="true" and sect~=nil) then
					table.remove(hides, k)
				end
			end
		end
		local nearest_cover_id = hides[1]:id()
		local nearest_cover_dist = hides[1]:position():distance_to(db.get_actor():position())
		for k,v in pairs(hides) do
			if not (db.storage[v:id()]) then 
				return nil
			end
			
			if db.storage[v:id()].object:inside(db.get_actor():position()) then
				return v:id()
			end
			local dist = v:position():distance_to(db.get_actor():position())
			if(dist<nearest_cover_dist) then
				if(v.condlist) then
					local sect = xr_logic.pick_section_from_condlist(db.get_actor(), nil, v.condlist)
					if(sect=="true") then
						nearest_cover_id = v:id()
						nearest_cover_dist = dist
					end
				else
					nearest_cover_id = v:id()
					nearest_cover_dist = dist
				end
			end
		end
		if(nearest_cover_id==hides[1]:id()) then
			if(hides[1].condlist) then
				local sect = xr_logic.pick_section_from_condlist(db.get_actor(), nil, hides[1].condlist)
				if(sect~="true" and sect~=nil) then
					return nil
				end
			end
		end
		return nearest_cover_id
	else
		return nil
	end
end

function CSurgeManager:update()
	if(device().precache_frame > 1) then
		return
	end
	
	if not (db.get_actor()) then
		return
	end
	
	if (OnServer()) then
		self:updateServer()
	else 
		self:updateClient()
	end
end

function CSurgeManager:update_surge_state()
	local cover = self:get_nearest_cover()
	if(cover==nil and self.count==0) then
		self:init_surge_covers()
	end		
	
	print_msg("UPDATE SURGE DIFF: " .. tostring(diff_sec) .. " | Self Surge TIME: " .. tostring(self.surge_time) )
 
	if(diff_sec>=self.surge_time) then
		print_msg(" Say Phrase 3 ")

		if(level.name()=="zaton") then
			xr_sound.set_sound_play_self(db.get_actor():id(), "zat_a2_stalker_barmen_after_surge")
		elseif(level.name()=="jupiter") then
			xr_sound.set_sound_play_self(db.get_actor():id(), "jup_a6_stalker_medik_after_surge")
		else
			xr_sound.set_sound_play_self(db.get_actor():id(), "pri_a17_kovalsky_after_surge")
		end
 		self:end_surge()
		return
	end
	
	self:launch_rockets()

	if(self.effector_set) then
		level.set_pp_effector_factor(surge_shock_pp_eff, diff_sec/90, 0.1)
	end
	
	if(self.blowout_sound) then
		xr_sound.set_volume_sound_looped(db.get_actor():id(), "blowout_rumble", diff_sec/180)
	end
	
	if(diff_sec>=140 and not(self.ui_disabled) and (cover==nil or not(db.storage[cover].object:inside(db.get_actor():position())))) then
		local att = 1-(185-diff_sec)/(185-140)
		att = att*att*att*0.3
		local h = hit()
		h.type = hit.telepatic
		h.power = att
		h.impulse = 0.0
		h.direction = vector():set(0,0,1)
		h.draftsman = db.get_actor()			
		db.get_actor():hit(h)
	end
	
	if(diff_sec>=0) and not(self.task_given)then
		print_msg("Give Task And Say Phrase 1")
 		if(level.name()=="zaton") then
			xr_sound.set_sound_play_self(db.get_actor():id(), "zat_a2_stalker_barmen_surge_phase_1")
		elseif(level.name()=="jupiter") then
			xr_sound.set_sound_play_self(db.get_actor():id(), "jup_a6_stalker_medik_phase_1")
		elseif not has_alife_info("pri_b305_fifth_cam_end") then
			xr_sound.set_sound_play_self(db.get_actor():id(), "pri_a17_kovalsky_surge_phase_1")
		end
 
		self:give_surge_hide_task()
		self.task_given = true
	end
	
	if(diff_sec>=35) and not(self.blowout_sound)then
		xr_sound.set_sound_play_self(db.get_actor():id(), "blowout_begin")
		xr_sound.play_sound_looped(db.get_actor():id(), "blowout_rumble")
		xr_sound.set_volume_sound_looped(db.get_actor():id(), "blowout_rumble", 0.25)
		self.blowout_sound = true
	end
	
	if(diff_sec>=100) and not(self.effector_set) then
		level.add_pp_effector("surge_shock.ppe", surge_shock_pp_eff, true)
		self.effector_set = true
	end
	
	if(diff_sec>=140) and not(self.second_message_given) then
		print_msg(" Say Phrase 2")

 		if(level.name()=="zaton") then
			xr_sound.set_sound_play_self(db.get_actor():id(), "zat_a2_stalker_barmen_surge_phase_2")
		elseif(level.name()=="jupiter") then
			xr_sound.set_sound_play_self(db.get_actor():id(), "jup_a6_stalker_medik_phase_2")
		else
			xr_sound.set_sound_play_self(db.get_actor():id(), "pri_a17_kovalsky_surge_phase_2")
		end
 		xr_sound.play_sound_looped(db.get_actor():id(), "surge_earthquake_sound_looped")
		level.add_cam_effector("camera_effects\\earthquake.anm", earthquake_cam_eff, true, "")
		self.second_message_given = true
	end

	if(diff_sec>=185) and not(self.ui_disabled) then
		self:kill_all_unhided()
		self.ui_disabled = true
	end
end

function CSurgeManager:updateClient()	
	if(prev_sec~=diff_sec) then
		prev_sec = diff_sec 
		printf_msg("------>diff_sec="..tostring(diff_sec))	
		self:update_surge_state()
	end	
end

function CSurgeManager:updateServer()
 	if not(self.started) then
		local g_time = game.get_game_time()

  		if(self.time_forwarded) then
			log("--->delta="..tostring(self._delta))
			log("--->diffSec="..tostring(g_time:diffSec(self.last_surge_time)))
			local diff = math.abs(self._delta - g_time:diffSec(self.last_surge_time))
			log("--->diff="..tostring(diff))
			if(diff<3600) then
				self._delta = 3*3600+g_time:diffSec(self.last_surge_time)
			end
			self.time_forwarded = false
		end
 
		if (g_time:diffSec(self.last_surge_update) > 1) then 
			local packet = mp_events.gen_event('SURGE')
			packet:w_u32(0)
			mp_events.send_broadcast(packet)
	
			self.last_surge_update = g_time
			return
		end 

		if(g_time:diffSec(self.last_surge_time) < self._delta) then
			return
		end

		if not(self:get_nearest_cover()) then
			return
		end

		self:start()
		return
	end
 	
	diff_sec = math.ceil(game.get_game_time():diffSec(self.inited_time) / level.get_time_factor())
	
	if(prev_sec~=diff_sec) then
		prev_sec = diff_sec
		
		local packet = mp_events.gen_event('SURGE')
		packet:w_u32(diff_sec)
		mp_events.send_broadcast(packet)
 	
		--print_msg("------>diff_sec="..tostring(diff_sec))
		
		local cover = self:get_nearest_cover()
		if(cover==nil and self.count==0) then
			self:init_surge_covers()
 		end

		if (diff_sec >= 0 and not self.started_weather) then
			print_msg("Setup Weather FX")

			level.set_weather_fx("fx_surge_day_3")
			self.started_weather = true
		end

		self:update_surge_state()
	
		-- if(diff_sec>=35) and not(self.blowout_sound)then
		-- 	self.blowout_sound = true
		-- end
		-- 
		-- if(diff_sec>=100) and not(self.effector_set) then
		--  	self.effector_set = true
		-- end
		-- 
		-- if(diff_sec>=140) and not(self.second_message_given) then
		-- 	self.second_message_given = true
		-- end
		-- 	
		-- if(diff_sec>=185) and not(self.ui_disabled) then
		-- 	--self:kill_all_unhided()
		-- 	self.ui_disabled = true
		-- end
	end	
		
end


function CSurgeManager:console_start()
	if not (self.started) then
		self:start(true)
	end
end

function CSurgeManager:clientRecive(packet)	
	if (db.get_actor() == nil) then 
		return
	end
 	diff_sec = packet:r_u32()
	if (diff_sec < 1) then 
		if (self.started == true) then
			self:end_surge(false)
		end
 		return
	end
 	if (self.started == false) then
		self:start(true)
	end
end




function CSurgeManager:start(manual)
	if not (self.initialized) then
 		self:initialize()
	end
	
	local Y, M, D, h, m, s, ms = 0, 0, 0, 0, 0, 0, 0
	Y, M, D, h, m, s, ms = self.last_surge_time:get(Y, M, D, h, m, s, ms)
	if(manual) then
		self.inited_time = game.get_game_time()
	else
		self.inited_time:set(Y, M, D, h, m, s + self._delta, ms)
	end

	diff_sec = math.ceil(game.get_game_time():diffSec(self.inited_time)/level.get_time_factor())
	log("--->start diff_sec="..tostring(diff_sec))
	
	if(diff_sec+6>self.surge_time)then
		printf("Surge skipped while time forwarding!")
		self:skip_surge()
	else
		self.started = true
		self.finished = false
	end
end

function CSurgeManager:skip_surge()
	local Y, M, D, h, m, s, ms = 0, 0, 0, 0, 0, 0, 0
	Y, M, D, h, m, s, ms = self.inited_time:get(Y, M, D, h, m, s, ms)
	self.last_surge_time:set(Y, M, D, h, m, s + self.surge_time, ms)

	self.started 			= false
	self.finished 			= true
	self.levels_respawn 	= {zaton = true, jupiter = true, pripyat = true}
	self._delta 			= math.random(MIN_SURGE_TIME, MAX_SURGE_TIME)
	self.surge_message 		= ""
	self.surge_task_sect 	= ""
	self.task_given 		= false

	self.effector_set			= false
	self.second_message_given 	= false
	self.ui_disabled			= false
	self.blowout_sound			= false
	prev_sec				= 0

	self:respawn_artefacts_and_replace_anomaly_zone()
	xr_statistic.inc_surges_counter()

	diff_sec = 0

	if (not self.skip_message) then
		news_manager.send_tip(db.get_actor(), "st_surge_while_asleep", nil, "recent_surge", nil, nil)
		self.skip_message = true
	end
end

function CSurgeManager:end_surge(manual)
	print_msg("Surge Ended !!!")

	self.started 			= false
	self.finished 			= true
	self.levels_respawn 	= {zaton = true, jupiter = true, pripyat = true}
	self.last_surge_time 	= game.get_game_time()
	self._delta 			= math.random(MIN_SURGE_TIME, MAX_SURGE_TIME)
	self.surge_message 		= ""
	self.surge_task_sect 	= ""
	self.task_given 		= false
	self.started_weather 	= false
	
	if (db.get_actor()) then 
		if(self.blowout_sound) then
			xr_sound.stop_sound_looped(db.get_actor():id(), "blowout_rumble")
		end
		if(self.second_message_given) then
			xr_sound.stop_sound_looped(db.get_actor():id(), "surge_earthquake_sound_looped")
		end
	else 
		xr_sound.stop_all_sounds()
	end
 
	level.remove_pp_effector(surge_shock_pp_eff)
	level.remove_cam_effector(earthquake_cam_eff)

	if(manual or (self.time_forwarded and level_weathers.get_weather_manager().weather_fx)) then
		level.stop_weather_fx()
 		--level_weathers.get_weather_manager():forced_weather_change()
		
		local packet = mp_events.gen_event('SURGE')
		packet:w_u32(65555)
		mp_events.send_broadcast(packet)
	end

	self.effector_set 			= false
	self.second_message_given 	= false
	self.ui_disabled  			= false
	self.blowout_sound			= false
	prev_sec					= 0

	for k,v in pairs(db.signal_light) do
		v:stop_light()
		v:stop()
	end

	if self.loaded then
		self:kill_all_unhided()
	end

	if (OnServer()) then 
		self:respawn_artefacts_and_replace_anomaly_zone()
		xr_statistic.inc_surges_counter()
	end

	diff_sec = 0
end

function CSurgeManager:respawn_artefacts_and_replace_anomaly_zone()
	local lvl_nm = level.name()
	
	if(self.levels_respawn[lvl_nm]) then
		self.levels_respawn[lvl_nm] = false
	end
	
	local anomalies = db.anomaly_by_name
	for k,v in pairs(anomalies) do
		v:respawn_artefacts_and_replace_anomaly_zone()
 	end
	pda.change_anomalies_names()
end

function CSurgeManager:give_surge_hide_task()
	if(self.surge_message~="empty") then
		local mess = ""
		if(self.surge_message=="") then
			local time = 0
			mess = game.translate_string("hide_from_surge_message")
		else
			mess = game.translate_string(self.surge_message)
		end
	end
	
	-- Se7kills 
	-- TODO FIX TASKS MANAGER FOR MP

	-- if(self.surge_task_sect~="empty") then
	-- 		if(self.surge_task_sect=="") then
	-- 			task_manager.get_task_manager():give_task("hide_from_surge")
	-- 		else
	-- 			task_manager.get_task_manager():give_task(self.surge_task_sect)
	-- 		end
	-- end
end

function CSurgeManager:kill_all_unhided()
	local cover = self:get_nearest_cover()
	
	if(db.get_actor() and db.get_actor():alive()) then
		if not(cover and db.storage[cover] and db.storage[cover].object:inside(db.get_actor():position())) then		
 
			
			level.add_cam_effector("camera_effects\\surge_02.anm", sleep_cam_eff, false, "surge_manager.surge_callback")
			level.add_pp_effector("surge_fade.ppe", sleep_fade_pp_eff, false)
			db.get_actor().health = db.get_actor().health-0.05
		end
	end
end

function surge_callback()
	level.add_cam_effector("camera_effects\\surge_01.anm", sleep_cam_eff, false, "surge_manager.surge_callback2")
--	level.stop_weather_fx()
--	level.change_game_time(0,0,15)
--	level_weathers.get_weather_manager():forced_weather_change()
end

function surge_callback2()
end

function CSurgeManager:launch_rockets()
	for k,v in pairs(db.signal_light) do
		if not(v:is_flying()) then
			v:launch()
		end
	end
end

--[[
function CSurgeManager:save(packet)
	set_save_marker(packet, "save", false, "SurgeHide")
	packet:w_bool(self.finished)
	packet:w_bool(self.started)
	utils.w_CTime(packet, self.last_surge_time)
	if(self.started) then
		utils.w_CTime(packet, self.inited_time)

		packet:w_bool(self.levels_respawn.zaton)
		packet:w_bool(self.levels_respawn.jupiter)
		packet:w_bool(self.levels_respawn.pripyat)

		packet:w_bool(self.task_given)
		packet:w_bool(self.effector_set)
		packet:w_bool(self.second_message_given)
		packet:w_bool(self.ui_disabled)
		packet:w_bool(self.blowout_sound)

		packet:w_stringZ(self.surge_message)
		packet:w_stringZ(self.surge_task_sect)
	end
	packet:w_u32(self._delta)
	set_save_marker(packet, "save", true, "SurgeHide")
end

function CSurgeManager:load(packet)
	set_save_marker(packet, "load", false, "SurgeHide")
	self:initialize()
	self.finished = packet:r_bool()
	self.started = packet:r_bool()
	self.last_surge_time = utils.r_CTime(packet)
	if(self.started) then
		self.inited_time = utils.r_CTime(packet)

		self.levels_respawn.zaton = packet:r_bool()
		self.levels_respawn.jupiter = packet:r_bool()
		self.levels_respawn.pripyat = packet:r_bool()

		self.task_given = packet:r_bool()
		self.effector_set = packet:r_bool()
		self.second_message_given = packet:r_bool()
		self.ui_disabled = packet:r_bool()
		self.blowout_sound = packet:r_bool()

		self.surge_message = packet:r_stringZ()
		self.surge_task_sect = packet:r_stringZ()
	end
	self._delta = packet:r_u32()
	self.loaded = true
	set_save_marker(packet, "load", true, "SurgeHide")
end
]]

--------------------------------------------------------------------------------
function get_surge_manager()
	if surge_manager == nil then
		surge_manager = CSurgeManager()
	end
	return surge_manager
end

function start_surge()
	local m = get_surge_manager()	
	if(m:get_nearest_cover()) then
		m:start(true)
	else
		printf("Error: Surge covers are not set! Can't manually start")
	end
end

function actor_in_cover()
	local m = get_surge_manager()
	local cover_id = m:get_nearest_cover()
	if (cover_id ~= nil) and (db.storage[cover_id].object:inside(db.get_actor():position())) then
		return true
	else
		return false
	end
end

function stop_surge()
	local m = get_surge_manager()
	if(m.started) then
		m:end_surge(true)
	end
end

function get_task_descr()
	local descr = ""
	if(actor_in_cover()) then
		descr = game.translate_string("hide_from_surge_descr_2_a")
	else
		descr = game.translate_string("hide_from_surge_descr_1_a")
	end
	return descr
end

function get_task_target()
	local m = get_surge_manager()
	if(actor_in_cover()) then
		return nil
	end
	return m:get_nearest_cover()
end

function set_surge_message(mess)
	local m = get_surge_manager()
	m.surge_message = mess
end

function set_surge_task(task)
	local m = get_surge_manager()
	m.surge_task_sect = task
end

function is_started()
	local m = get_surge_manager()
	return m.started
end

function is_killing_all()
	local m = get_surge_manager()
	if(m.started and m.ui_disabled) then
		return true
	end
	return false
end

function is_finished()
	local m = get_surge_manager()
	return m.finished == true
end

function resurrect_skip_message()
	local m = get_surge_manager()
	m.skip_message = false
end

function sound_started()
	local m = get_surge_manager()
	return m.started and m.blowout_sound
end
