--------------------------------------------------------------------------------
-- Created: 13.05.2009 ---------------------------------------------------------
-- Description:	local network login page ---------------------------------------
-- Author: Alexander Maniluk ---------------------------------------------------
-- Mail: loopzilla@gsc-game.kiev.ua --------------------------------------------
-- (c)GSC Game World 2009 ------------------------------------------------------
--------------------------------------------------------------------------------

class "localnet_page" (CUIScriptWnd)
function localnet_page:__init() super()
   self:InitControls()
   self:InitCallbacks()
   self:LoadTextFilds()
end


function localnet_page:LoadTextFilds()	
	local IP, PORT, NAME = nil
	IP 	 = accounts_coop.GetAccountIP()
	PORT = accounts_coop.GetAccountPort()
	NAME = accounts_coop.GetAccountLogin() 
	
	if (IP ~= nil) then 
		self.lp_ip_server:SetText( IP )
	end
	if (PORT ~= nil) then  
		self.lp_port:SetText( PORT )
	end
 	if (NAME ~= nil) then 
		self.lp_nickname:SetText( NAME )
	end
end

function localnet_page:SaveAuth(IP, PORT, LOGIN)
	accounts_coop.SaveAccount(LOGIN, IP, PORT)
end

function localnet_page:InitControls()
	local xml = CScriptXmlInit()
	xml:ParseFile("ui_mm_mp_localnet.xml")

--	self:SetWndRect(Frect():set(0,0,1024,768))
	
	self:SetWndRect(Frect():set(0,0,1920,1080))

	
	self:Enable(true)
	xml:InitStatic("background", self)

	self.login_page = CUIWindow()
	xml:InitWindow("login_page", 0, self.login_page)
	
	self.login_page:SetAutoDelete(true)
	self:AttachChild(self.login_page)
	
	xml:InitWindow("login_page", 0, self.login_page)
	self.lp_header_login = xml:InitTextWnd("login_page:cap_header_login", self.login_page)

	local button = nil
	button = xml:Init3tButton("login_page:button_login", self.login_page)
	self:Register(button, "btn_login")
    self.btn_login = button

	button = xml:Init3tButton("login_page:button_cancel", self.login_page)
	self:Register(button, "btn_cancel")
    self.btn_cancel = button
--------------------------------------------------------------------------------


	xml:InitTextWnd("login_page:cap_login", self.login_page)
	self.lp_nickname = xml:InitEditBox("login_page:edit_login", self.login_page)
	self:Register(self.lp_nickname, "lp_edit_nickname")
	
--	xml:InitTextWnd("login_page:cap_password", self.login_page)
-- 	self.lp_password = xml:InitEditBox("login_page:edit_password", self.login_page)
--	self:Register(self.lp_password, "lp_edit_password")
	
	xml:InitTextWnd("login_page:cap_ipserver", self.login_page)
 	self.lp_ip_server = xml:InitEditBox("login_page:edit_ip_server", self.login_page)
	self:Register(self.lp_ip_server, "lp_edit_ip_server")
	
	xml:InitTextWnd("login_page:cap_port", self.login_page)
 	self.lp_port = xml:InitEditBox("login_page:edit_port", self.login_page)
	self:Register(self.lp_port, "lp_edit_port")
	
	
	self.gs_login_message_box = CUIMessageBoxEx()
	self:Register(self.gs_login_message_box, "gs_message_box")
 
	self.lp_nickname:CaptureFocus(true)
end

function localnet_page:InitCallbacks()
	self:AddCallback("btn_login", ui_events.BUTTON_CLICKED, self.OnBtnLogin, self)
	self:AddCallback("btn_cancel", ui_events.BUTTON_CLICKED, self.OnBtnCancel, self)
	--self:AddCallback("lp_check_remember_me", ui_events.BUTTON_CLICKED, self.OnBtnRememberMe, self)
	
	--self:AddCallback("lp_edit_nickname", ui_events.EDIT_TEXT_COMMIT, self.OnEditLPNicknameChanged, self)
	self:AddCallback("gs_message_box", ui_events.MESSAGE_BOX_OK_CLICKED, self.OnMsgOk, self)
end 

function localnet_page:OnBtnLogin()
	local IP    = self.lp_ip_server:GetText()
 	local PORT 	= self.lp_port:GetText()
	local LOGIN = self.lp_nickname:GetText()
	
	
	local cmd = "start client("..IP.."/port="..PORT.."/name="..LOGIN..")" 
	local console = get_console()
	console:execute(cmd)
	
	self:SaveAuth(IP, PORT, LOGIN)
end

--[[
function localnet_page:OnBtnLogin()
	self.owner.l_mgr:login_offline(self.lp_nickname:GetText(), login_operation_cb(self, self.LoginOperationResult))
end
]]

function localnet_page:LoginOperationResult(profile, descr)

end

function localnet_page:OnMsgOk()
	printf_msg("OnMsgOk")
end

function localnet_page:OnBtnCancel()
	self:HideDialog()
	self.owner:ShowDialog(true)
	self.owner:Show(true)
end

function localnet_page:OnBtnRememberMe()
	self.owner.l_mgr:save_remember_me_to_registry(self.lp_check_remember_me:GetCheck())
end

function localnet_page:OnEditLPNicknameChanged()
    self:OnBtnLogin()
end

function localnet_page:OnKeyboard(dik, keyboard_action)
	CUIScriptWnd.OnKeyboard(self,dik,keyboard_action)

	local bind = dik_to_bind(dik)
	local console = get_console()

	if keyboard_action == ui_events.WINDOW_KEY_PRESSED then
		if dik == DIK_keys.DIK_ESCAPE then
			self:OnBtnCancel()
		end
	end
	
	return true
end